version: '2'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn DWmonitoring.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/gkavach-dwm
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: DWmonitoring.settings
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres

volumes:
  postgres_data:
