# Generated by Django 5.0.6 on 2024-06-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_organization_about_remove_organization_vision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
