# Generated by Django 5.0.7 on 2024-07-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dark_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackmarket',
            name='posted_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='posted_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='posted_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='piiexposure',
            name='posted_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stealerlogs',
            name='posted_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
